export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",

  // Posts
//   POST_NOT_FOUND: "POST_NOT_FOUND",
//   POST_NOT_AUTHORIZED: "POST_NOT_AUTHORIZED",

  // System
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;